import type { NextPage } from 'next'
import Head from 'next/head'
import FocusGraph from '../components/Graphs/GraphWrapper'
import Header from '../components/Header/Header'
import Searchbox from '../components/Searchbox/Searchbox'
import SearchResults from '../components/SearchResults/SearchResults'
import { useState } from 'react'
//import styles from '../styles/Home.module.css'

interface node {
  id: string
}
interface link {
  source: string,
  target: string
}
interface record {
  "_id": Object
  "id": string,
  "number": number,
  "address": string,    
  "tx_id": string,    
  "sat_ordinal": string,  
  "mime_type": string,
  "content_type": string,    
  "timestamp": number,  
  "recursive": boolean,
  "recursion_refs": string[],
  "content": string
}

interface ChildProps {
  graphData: {nodes: node[], links: link[]},
  searchResults: record[]
}

const Home: NextPage<ChildProps> = () => {

  const[ comp, setComp ] = useState(0)
  const[ dataObj, setDataObj ] = useState<ChildProps>({
    graphData: { nodes: [], links: [] },
    searchResults: [],
  })
  
  const setComponent = (comp: number, dataObj: ChildProps) => {
    setComp(comp)
    setDataObj(dataObj)
    //dataObj = dataObj
    console.log(dataObj)
    console.log(comp)
  }
  return (
    <div className='bg-black'>
      <Head>
        <title>Ordverse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <Searchbox getCompData={setComponent}/>
        {comp === 0 ? <FocusGraph /> : <SearchResults graphData={dataObj.graphData} searchResults={dataObj.searchResults}/>}
      </main>
    </div>

  )
}

export default Home
